// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clip} from '../models';
import {context} from '../models';

export function Add(arg1:string):Promise<void>;

export function GetAll():Promise<Array<clip.CopiedContent>>;

export function GetContext():Promise<context.Context>;

export function SetContext(arg1:context.Context):Promise<void>;
