// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['clip']['ClipboardManager']['Add'](arg1);
}

export function ClearHistory() {
  return window['go']['clip']['ClipboardManager']['ClearHistory']();
}

export function GetCurrentContext() {
  return window['go']['clip']['ClipboardManager']['GetCurrentContext']();
}

export function GetHistory() {
  return window['go']['clip']['ClipboardManager']['GetHistory']();
}

export function Select(arg1) {
  return window['go']['clip']['ClipboardManager']['Select'](arg1);
}
