// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['clip']['ClipboardManager']['Add'](arg1);
}

export function GetAll() {
  return window['go']['clip']['ClipboardManager']['GetAll']();
}

export function GetContext() {
  return window['go']['clip']['ClipboardManager']['GetContext']();
}

export function SetContext(arg1) {
  return window['go']['clip']['ClipboardManager']['SetContext'](arg1);
}
