// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clip} from '../models';

export function Add(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetCurrentContext():Promise<string>;

export function GetHistory():Promise<Array<clip.ClipboardItem>>;

export function Select(arg1:number):Promise<boolean>;
