// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}
